name: Test

on:
    push:
    pull_request:
    
jobs:
    run_unit_tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                python -m pip install -r requirements.txt
            
            - name: Run unit tests
              run: |
                source venv/bin/activate
                python -m unittest discover -v